/**
 * Sample Library Catalog
 *
 * Organizes 223 samples into categories for easy browsing.
 * Supports voice-aware filtering (e.g., kicks for KICK voice only).
 */

export interface LibrarySample {
  id: string;           // e.g. "kick-01"
  name: string;         // e.g. "House Kick 01 - G#m"
  key: string;          // e.g. "G#m" (extracted from filename, may be empty)
  path: string;         // e.g. "/samples/library/kicks/kick-01.wav"
  category: SampleCategory;
}

export type SampleCategory = "kicks" | "snares" | "rims" | "hats" | "claps" | "cymbals" | "toms" | "percussions" | "snaps" | "sfx";

/**
 * Maps each voice (0-11) to its appropriate sample categories.
 * This determines which samples appear in the SampleBrowser for each pad.
 */
export const VOICE_CATEGORIES: Record<number, SampleCategory[]> = {
  0: ["kicks"],                           // KICK
  1: ["snares", "rims", "claps"],         // SNARE
  2: ["claps", "snaps", "snares"],        // CLAP
  3: ["toms", "percussions"],             // TOM LO
  4: ["toms", "percussions"],             // TOM MID
  5: ["toms", "percussions"],             // TOM HI
  6: ["hats"],                            // HH CL (closed)
  7: ["hats", "cymbals"],                 // HH OP (open)
  8: ["cymbals"],                         // CYMBAL
  9: ["cymbals", "hats"],                 // RIDE
  10: ["percussions", "snaps", "sfx"],    // PERC 1
  11: ["percussions", "snaps", "sfx"],    // PERC 2
};

export const SAMPLE_LIBRARY: LibrarySample[] = [
  { id: 'kick-01', name: 'House Kick 01 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-01.wav', category: 'kicks' },
  { id: 'kick-02', name: 'House Kick 02 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-02.wav', category: 'kicks' },
  { id: 'kick-03', name: 'House Kick 03 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-03.wav', category: 'kicks' },
  { id: 'kick-04', name: 'House Kick 04 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-04.wav', category: 'kicks' },
  { id: 'kick-05', name: 'House Kick 05 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-05.wav', category: 'kicks' },
  { id: 'kick-06', name: 'House Kick 06 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-06.wav', category: 'kicks' },
  { id: 'kick-07', name: 'House Kick 07 - Dm', key: 'Dm', path: '/samples/library/kicks/kick-07.wav', category: 'kicks' },
  { id: 'kick-08', name: 'House Kick 08 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-08.wav', category: 'kicks' },
  { id: 'kick-09', name: 'House Kick 09 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-09.wav', category: 'kicks' },
  { id: 'kick-10', name: 'House Kick 10 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-10.wav', category: 'kicks' },
  { id: 'kick-11', name: 'House Kick 11 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-11.wav', category: 'kicks' },
  { id: 'kick-12', name: 'House Kick 12 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-12.wav', category: 'kicks' },
  { id: 'kick-13', name: 'House Kick 13 - A#m or A#', key: 'A#m or A#', path: '/samples/library/kicks/kick-13.wav', category: 'kicks' },
  { id: 'kick-14', name: 'House Kick 14 - Dm', key: 'Dm', path: '/samples/library/kicks/kick-14.wav', category: 'kicks' },
  { id: 'kick-15', name: 'House Kick 15 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-15.wav', category: 'kicks' },
  { id: 'kick-16', name: 'House Kick 16 - Dm', key: 'Dm', path: '/samples/library/kicks/kick-16.wav', category: 'kicks' },
  { id: 'kick-17', name: 'House Kick 17 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-17.wav', category: 'kicks' },
  { id: 'kick-18', name: 'House Kick 18 - Fm', key: 'Fm', path: '/samples/library/kicks/kick-18.wav', category: 'kicks' },
  { id: 'kick-19', name: 'House Kick 19 - F#m', key: 'F#m', path: '/samples/library/kicks/kick-19.wav', category: 'kicks' },
  { id: 'kick-20', name: 'House Kick 20 - Am', key: 'Am', path: '/samples/library/kicks/kick-20.wav', category: 'kicks' },
  { id: 'kick-21', name: 'House Kick 21 - A', key: 'A', path: '/samples/library/kicks/kick-21.wav', category: 'kicks' },
  { id: 'kick-22', name: 'House Kick 22 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-22.wav', category: 'kicks' },
  { id: 'kick-23', name: 'House Kick 23 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-23.wav', category: 'kicks' },
  { id: 'kick-24', name: 'House Kick 24 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-24.wav', category: 'kicks' },
  { id: 'kick-25', name: 'House Kick 25 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-25.wav', category: 'kicks' },
  { id: 'kick-26', name: 'House Kick 26 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-26.wav', category: 'kicks' },
  { id: 'kick-27', name: 'House Kick 27 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-27.wav', category: 'kicks' },
  { id: 'kick-28', name: 'House Kick 28 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-28.wav', category: 'kicks' },
  { id: 'kick-29', name: 'House Kick 29 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-29.wav', category: 'kicks' },
  { id: 'kick-30', name: 'House Kick 30 - Am', key: 'Am', path: '/samples/library/kicks/kick-30.wav', category: 'kicks' },
  { id: 'kick-31', name: 'House Kick 31 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-31.wav', category: 'kicks' },
  { id: 'kick-32', name: 'House Kick 32 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-32.wav', category: 'kicks' },
  { id: 'kick-33', name: 'House Kick 33 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-33.wav', category: 'kicks' },
  { id: 'kick-34', name: 'House Kick 34 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-34.wav', category: 'kicks' },
  { id: 'kick-35', name: 'House Kick 35 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-35.wav', category: 'kicks' },
  { id: 'kick-36', name: 'House Kick 36 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-36.wav', category: 'kicks' },
  { id: 'kick-37', name: 'House Kick 37 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-37.wav', category: 'kicks' },
  { id: 'kick-38', name: 'House Kick 38 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-38.wav', category: 'kicks' },
  { id: 'kick-39', name: 'House Kick 39 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-39.wav', category: 'kicks' },
  { id: 'kick-40', name: 'House Kick 40 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-40.wav', category: 'kicks' },
  { id: 'kick-41', name: 'House Kick 41 - G#m', key: 'G#m', path: '/samples/library/kicks/kick-41.wav', category: 'kicks' },
  { id: 'snare-01', name: 'House Snare 01 - G#m', key: 'G#m', path: '/samples/library/snares/snare-01.wav', category: 'snares' },
  { id: 'snare-02', name: 'House Snare 02 - Fm', key: 'Fm', path: '/samples/library/snares/snare-02.wav', category: 'snares' },
  { id: 'snare-03', name: 'House Snare 03 - G#m', key: 'G#m', path: '/samples/library/snares/snare-03.wav', category: 'snares' },
  { id: 'snare-04', name: 'House Snare 04 - G#m', key: 'G#m', path: '/samples/library/snares/snare-04.wav', category: 'snares' },
  { id: 'snare-05', name: 'House Snare 05 - G#m', key: 'G#m', path: '/samples/library/snares/snare-05.wav', category: 'snares' },
  { id: 'snare-06', name: 'House Snare 06 - G#m', key: 'G#m', path: '/samples/library/snares/snare-06.wav', category: 'snares' },
  { id: 'snare-07', name: 'House Snare 07 - G#m', key: 'G#m', path: '/samples/library/snares/snare-07.wav', category: 'snares' },
  { id: 'snare-08', name: 'House Snare 08 - G#m', key: 'G#m', path: '/samples/library/snares/snare-08.wav', category: 'snares' },
  { id: 'snare-09', name: 'House Snare 09 - G#m', key: 'G#m', path: '/samples/library/snares/snare-09.wav', category: 'snares' },
  { id: 'snare-10', name: 'House Snare 10 - G#m', key: 'G#m', path: '/samples/library/snares/snare-10.wav', category: 'snares' },
  { id: 'snare-11', name: 'House Snare 11 - G#m', key: 'G#m', path: '/samples/library/snares/snare-11.wav', category: 'snares' },
  { id: 'snare-12', name: 'House Snare 12 - G#m', key: 'G#m', path: '/samples/library/snares/snare-12.wav', category: 'snares' },
  { id: 'snare-13', name: 'House Snare 13 - G#m', key: 'G#m', path: '/samples/library/snares/snare-13.wav', category: 'snares' },
  { id: 'snare-14', name: 'House Snare 14 - G#m', key: 'G#m', path: '/samples/library/snares/snare-14.wav', category: 'snares' },
  { id: 'snare-15', name: 'House Snare 15 - G#m', key: 'G#m', path: '/samples/library/snares/snare-15.wav', category: 'snares' },
  { id: 'snare-16', name: 'House Snare 16 - G#m', key: 'G#m', path: '/samples/library/snares/snare-16.wav', category: 'snares' },
  { id: 'snare-17', name: 'House Snare 17 - G#m', key: 'G#m', path: '/samples/library/snares/snare-17.wav', category: 'snares' },
  { id: 'snare-18', name: 'House Snare 18 - G#m', key: 'G#m', path: '/samples/library/snares/snare-18.wav', category: 'snares' },
  { id: 'snare-19', name: 'House Snare 19 - G#m', key: 'G#m', path: '/samples/library/snares/snare-19.wav', category: 'snares' },
  { id: 'snare-20', name: 'House Snare 20 - G#m', key: 'G#m', path: '/samples/library/snares/snare-20.wav', category: 'snares' },
  { id: 'snare-21', name: 'House Snare 21 - C#m', key: 'C#m', path: '/samples/library/snares/snare-21.wav', category: 'snares' },
  { id: 'snare-22', name: 'House Snare 22 - G#m', key: 'G#m', path: '/samples/library/snares/snare-22.wav', category: 'snares' },
  { id: 'snare-23', name: 'House Snare 23 - G#m', key: 'G#m', path: '/samples/library/snares/snare-23.wav', category: 'snares' },
  { id: 'snare-24', name: 'House Snare 24 - G#m', key: 'G#m', path: '/samples/library/snares/snare-24.wav', category: 'snares' },
  { id: 'snare-25', name: 'House Snare 25 - G#m', key: 'G#m', path: '/samples/library/snares/snare-25.wav', category: 'snares' },
  { id: 'rim-01', name: 'House Rim 01 - G#m', key: 'G#m', path: '/samples/library/rims/rim-01.wav', category: 'rims' },
  { id: 'rim-02', name: 'House Rim 02 - G#m', key: 'G#m', path: '/samples/library/rims/rim-02.wav', category: 'rims' },
  { id: 'rim-03', name: 'House Rim 03 - G#m', key: 'G#m', path: '/samples/library/rims/rim-03.wav', category: 'rims' },
  { id: 'rim-04', name: 'House Rim 04 - G#m', key: 'G#m', path: '/samples/library/rims/rim-04.wav', category: 'rims' },
  { id: 'rim-05', name: 'House Rim 05 - G#m', key: 'G#m', path: '/samples/library/rims/rim-05.wav', category: 'rims' },
  { id: 'rim-06', name: 'House Rim 06 - G#m', key: 'G#m', path: '/samples/library/rims/rim-06.wav', category: 'rims' },
  { id: 'rim-07', name: 'House Rim 07 - G#m', key: 'G#m', path: '/samples/library/rims/rim-07.wav', category: 'rims' },
  { id: 'hat-01', name: 'House HiHat 01 - G#m', key: 'G#m', path: '/samples/library/hats/hat-01.wav', category: 'hats' },
  { id: 'hat-02', name: 'House HiHat 02 - G#m', key: 'G#m', path: '/samples/library/hats/hat-02.wav', category: 'hats' },
  { id: 'hat-03', name: 'House HiHat 03 - G#m', key: 'G#m', path: '/samples/library/hats/hat-03.wav', category: 'hats' },
  { id: 'hat-04', name: 'House HiHat 04 - G#m', key: 'G#m', path: '/samples/library/hats/hat-04.wav', category: 'hats' },
  { id: 'hat-05', name: 'House HiHat 05 - G#m', key: 'G#m', path: '/samples/library/hats/hat-05.wav', category: 'hats' },
  { id: 'hat-06', name: 'House HiHat 06 - G#m', key: 'G#m', path: '/samples/library/hats/hat-06.wav', category: 'hats' },
  { id: 'hat-07', name: 'House HiHat 07 - G#m', key: 'G#m', path: '/samples/library/hats/hat-07.wav', category: 'hats' },
  { id: 'hat-08', name: 'House HiHat 08 - Bm', key: 'Bm', path: '/samples/library/hats/hat-08.wav', category: 'hats' },
  { id: 'hat-09', name: 'House HiHat 09 - G#m', key: 'G#m', path: '/samples/library/hats/hat-09.wav', category: 'hats' },
  { id: 'hat-10', name: 'House HiHat 10 - G#m', key: 'G#m', path: '/samples/library/hats/hat-10.wav', category: 'hats' },
  { id: 'hat-11', name: 'House HiHat 11 - G#m', key: 'G#m', path: '/samples/library/hats/hat-11.wav', category: 'hats' },
  { id: 'hat-12', name: 'House HiHat 12 - G#m', key: 'G#m', path: '/samples/library/hats/hat-12.wav', category: 'hats' },
  { id: 'hat-13', name: 'House HiHat 13 - G#m', key: 'G#m', path: '/samples/library/hats/hat-13.wav', category: 'hats' },
  { id: 'hat-14', name: 'House HiHat 14 - G#m', key: 'G#m', path: '/samples/library/hats/hat-14.wav', category: 'hats' },
  { id: 'hat-15', name: 'House HiHat 15 - G#m', key: 'G#m', path: '/samples/library/hats/hat-15.wav', category: 'hats' },
  { id: 'hat-16', name: 'House HiHat 16 - G#m', key: 'G#m', path: '/samples/library/hats/hat-16.wav', category: 'hats' },
  { id: 'hat-17', name: 'House HiHat 17 - G#m', key: 'G#m', path: '/samples/library/hats/hat-17.wav', category: 'hats' },
  { id: 'hat-18', name: 'House HiHat 18 - G#m', key: 'G#m', path: '/samples/library/hats/hat-18.wav', category: 'hats' },
  { id: 'hat-19', name: 'House HiHat 19 - G#m', key: 'G#m', path: '/samples/library/hats/hat-19.wav', category: 'hats' },
  { id: 'hat-20', name: 'House HiHat 20 - G#m', key: 'G#m', path: '/samples/library/hats/hat-20.wav', category: 'hats' },
  { id: 'hat-21', name: 'House HiHat 21 - G#m', key: 'G#m', path: '/samples/library/hats/hat-21.wav', category: 'hats' },
  { id: 'hat-22', name: 'House HiHat 22 - G#m', key: 'G#m', path: '/samples/library/hats/hat-22.wav', category: 'hats' },
  { id: 'hat-23', name: 'House HiHat 23 - G#m or G#', key: 'G#m or G#', path: '/samples/library/hats/hat-23.wav', category: 'hats' },
  { id: 'hat-24', name: 'House HiHat 24 - G#m', key: 'G#m', path: '/samples/library/hats/hat-24.wav', category: 'hats' },
  { id: 'hat-25', name: 'House HiHat 25 - G#m', key: 'G#m', path: '/samples/library/hats/hat-25.wav', category: 'hats' },
  { id: 'hat-26', name: 'House HiHat 26 - C#m', key: 'C#m', path: '/samples/library/hats/hat-26.wav', category: 'hats' },
  { id: 'hat-27', name: 'House HiHat 27 - G#m', key: 'G#m', path: '/samples/library/hats/hat-27.wav', category: 'hats' },
  { id: 'clap-01', name: 'House Clap 01 - C#m', key: 'C#m', path: '/samples/library/claps/clap-01.wav', category: 'claps' },
  { id: 'clap-02', name: 'House Clap 02 - G#m', key: 'G#m', path: '/samples/library/claps/clap-02.wav', category: 'claps' },
  { id: 'clap-03', name: 'House Clap 03 - G#m', key: 'G#m', path: '/samples/library/claps/clap-03.wav', category: 'claps' },
  { id: 'clap-04', name: 'House Clap 04 - G#m', key: 'G#m', path: '/samples/library/claps/clap-04.wav', category: 'claps' },
  { id: 'clap-05', name: 'House Clap 05 - G#m', key: 'G#m', path: '/samples/library/claps/clap-05.wav', category: 'claps' },
  { id: 'clap-06', name: 'House Clap 06 - G#m', key: 'G#m', path: '/samples/library/claps/clap-06.wav', category: 'claps' },
  { id: 'clap-07', name: 'House Clap 07 - G#m', key: 'G#m', path: '/samples/library/claps/clap-07.wav', category: 'claps' },
  { id: 'clap-08', name: 'House Clap 08 - G#m', key: 'G#m', path: '/samples/library/claps/clap-08.wav', category: 'claps' },
  { id: 'clap-09', name: 'House Clap 09', key: '', path: '/samples/library/claps/clap-09.wav', category: 'claps' },
  { id: 'clap-10', name: 'House Clap 10 - G#m', key: 'G#m', path: '/samples/library/claps/clap-10.wav', category: 'claps' },
  { id: 'clap-11', name: 'House Clap 11 - G#m', key: 'G#m', path: '/samples/library/claps/clap-11.wav', category: 'claps' },
  { id: 'clap-12', name: 'House Clap 12 - G#m', key: 'G#m', path: '/samples/library/claps/clap-12.wav', category: 'claps' },
  { id: 'clap-13', name: 'House Clap 13 - G#m', key: 'G#m', path: '/samples/library/claps/clap-13.wav', category: 'claps' },
  { id: 'clap-14', name: 'House Clap 14 - G#m', key: 'G#m', path: '/samples/library/claps/clap-14.wav', category: 'claps' },
  { id: 'clap-15', name: 'House Clap 15 - G#m', key: 'G#m', path: '/samples/library/claps/clap-15.wav', category: 'claps' },
  { id: 'clap-16', name: 'House Clap 16 - G#m', key: 'G#m', path: '/samples/library/claps/clap-16.wav', category: 'claps' },
  { id: 'cymbal-01', name: 'House Cymbal 01 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-01.wav', category: 'cymbals' },
  { id: 'cymbal-02', name: 'House Cymbal 02 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-02.wav', category: 'cymbals' },
  { id: 'cymbal-03', name: 'House Cymbal 03 - B', key: 'B', path: '/samples/library/cymbals/cymbal-03.wav', category: 'cymbals' },
  { id: 'cymbal-04', name: 'House Cymbal 04 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-04.wav', category: 'cymbals' },
  { id: 'cymbal-05', name: 'House Cymbal 05 - Cm', key: 'Cm', path: '/samples/library/cymbals/cymbal-05.wav', category: 'cymbals' },
  { id: 'cymbal-06', name: 'House Cymbal 06 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-06.wav', category: 'cymbals' },
  { id: 'cymbal-07', name: 'House Cymbal 07 - Em', key: 'Em', path: '/samples/library/cymbals/cymbal-07.wav', category: 'cymbals' },
  { id: 'cymbal-08', name: 'House Cymbal 08 - Cm', key: 'Cm', path: '/samples/library/cymbals/cymbal-08.wav', category: 'cymbals' },
  { id: 'cymbal-09', name: 'House Cymbal 09 - Fm', key: 'Fm', path: '/samples/library/cymbals/cymbal-09.wav', category: 'cymbals' },
  { id: 'cymbal-10', name: 'House Cymbal 10 - Cm', key: 'Cm', path: '/samples/library/cymbals/cymbal-10.wav', category: 'cymbals' },
  { id: 'cymbal-11', name: 'House Cymbal 11 - Fm', key: 'Fm', path: '/samples/library/cymbals/cymbal-11.wav', category: 'cymbals' },
  { id: 'cymbal-12', name: 'House Cymbal 12 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-12.wav', category: 'cymbals' },
  { id: 'cymbal-13', name: 'House Cymbal 13', key: '', path: '/samples/library/cymbals/cymbal-13.wav', category: 'cymbals' },
  { id: 'cymbal-14', name: 'House Cymbal 14 - Fm', key: 'Fm', path: '/samples/library/cymbals/cymbal-14.wav', category: 'cymbals' },
  { id: 'cymbal-15', name: 'House Cymbal 15', key: '', path: '/samples/library/cymbals/cymbal-15.wav', category: 'cymbals' },
  { id: 'cymbal-16', name: 'House Cymbal 16', key: '', path: '/samples/library/cymbals/cymbal-16.wav', category: 'cymbals' },
  { id: 'cymbal-17', name: 'House Cymbal 17 - D#m', key: 'D#m', path: '/samples/library/cymbals/cymbal-17.wav', category: 'cymbals' },
  { id: 'cymbal-18', name: 'House Cymbal 18 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-18.wav', category: 'cymbals' },
  { id: 'cymbal-19', name: 'House Cymbal 19 - Fm', key: 'Fm', path: '/samples/library/cymbals/cymbal-19.wav', category: 'cymbals' },
  { id: 'cymbal-20', name: 'House Cymbal 20 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-20.wav', category: 'cymbals' },
  { id: 'cymbal-21', name: 'House Cymbal 21 - A#m', key: 'A#m', path: '/samples/library/cymbals/cymbal-21.wav', category: 'cymbals' },
  { id: 'cymbal-22', name: 'House Cymbal 22 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-22.wav', category: 'cymbals' },
  { id: 'cymbal-23', name: 'House Cymbal 23 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-23.wav', category: 'cymbals' },
  { id: 'cymbal-24', name: 'House Cymbal 24 - G#m', key: 'G#m', path: '/samples/library/cymbals/cymbal-24.wav', category: 'cymbals' },
  { id: 'tom-01', name: 'House Tom 01 - G#m', key: 'G#m', path: '/samples/library/toms/tom-01.wav', category: 'toms' },
  { id: 'tom-02', name: 'House Tom 02 - G#m', key: 'G#m', path: '/samples/library/toms/tom-02.wav', category: 'toms' },
  { id: 'tom-03', name: 'House Tom 03 - G#m', key: 'G#m', path: '/samples/library/toms/tom-03.wav', category: 'toms' },
  { id: 'tom-04', name: 'House Tom 04 - G#m', key: 'G#m', path: '/samples/library/toms/tom-04.wav', category: 'toms' },
  { id: 'tom-05', name: 'House Tom 05 - Cm', key: 'Cm', path: '/samples/library/toms/tom-05.wav', category: 'toms' },
  { id: 'tom-06', name: 'House Tom 06 - G#m', key: 'G#m', path: '/samples/library/toms/tom-06.wav', category: 'toms' },
  { id: 'tom-07', name: 'House Tom 07 - G#m', key: 'G#m', path: '/samples/library/toms/tom-07.wav', category: 'toms' },
  { id: 'tom-08', name: 'House Tom 08 - C', key: 'C', path: '/samples/library/toms/tom-08.wav', category: 'toms' },
  { id: 'tom-09', name: 'House Tom 09 - G#m', key: 'G#m', path: '/samples/library/toms/tom-09.wav', category: 'toms' },
  { id: 'tom-10', name: 'House Tom 10 - G#m', key: 'G#m', path: '/samples/library/toms/tom-10.wav', category: 'toms' },
  { id: 'tom-11', name: 'House Tom 11 - G#m', key: 'G#m', path: '/samples/library/toms/tom-11.wav', category: 'toms' },
  { id: 'tom-12', name: 'House Tom 12 - G#m', key: 'G#m', path: '/samples/library/toms/tom-12.wav', category: 'toms' },
  { id: 'tom-13', name: 'House Tom 13 - G#m', key: 'G#m', path: '/samples/library/toms/tom-13.wav', category: 'toms' },
  { id: 'perc-01', name: 'House Percussion 01 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-01.wav', category: 'percussions' },
  { id: 'perc-02', name: 'House Percussion 02 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-02.wav', category: 'percussions' },
  { id: 'perc-03', name: 'House Percussion 03 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-03.wav', category: 'percussions' },
  { id: 'perc-04', name: 'House Percussion 04 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-04.wav', category: 'percussions' },
  { id: 'perc-05', name: 'House Percussion 05 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-05.wav', category: 'percussions' },
  { id: 'perc-06', name: 'House Percussion 06 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-06.wav', category: 'percussions' },
  { id: 'perc-07', name: 'House Percussion 07 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-07.wav', category: 'percussions' },
  { id: 'perc-08', name: 'House Percussion 08 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-08.wav', category: 'percussions' },
  { id: 'perc-09', name: 'House Percussion 09 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-09.wav', category: 'percussions' },
  { id: 'perc-10', name: 'House Percussion 10 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-10.wav', category: 'percussions' },
  { id: 'perc-11', name: 'House Percussion 11 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-11.wav', category: 'percussions' },
  { id: 'perc-12', name: 'House Percussion 12 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-12.wav', category: 'percussions' },
  { id: 'perc-13', name: 'House Percussion 13 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-13.wav', category: 'percussions' },
  { id: 'perc-14', name: 'House Percussion 14 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-14.wav', category: 'percussions' },
  { id: 'perc-15', name: 'House Percussion 15 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-15.wav', category: 'percussions' },
  { id: 'perc-16', name: 'House Percussion 16 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-16.wav', category: 'percussions' },
  { id: 'perc-17', name: 'House Percussion 17 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-17.wav', category: 'percussions' },
  { id: 'perc-18', name: 'House Percussion 18', key: '', path: '/samples/library/percussions/perc-18.wav', category: 'percussions' },
  { id: 'perc-19', name: 'House Percussion 19 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-19.wav', category: 'percussions' },
  { id: 'perc-20', name: 'House Percussion 20 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-20.wav', category: 'percussions' },
  { id: 'perc-21', name: 'House Percussion 21', key: '', path: '/samples/library/percussions/perc-21.wav', category: 'percussions' },
  { id: 'perc-22', name: 'House Percussion 22 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-22.wav', category: 'percussions' },
  { id: 'perc-23', name: 'House Percussion 23 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-23.wav', category: 'percussions' },
  { id: 'perc-24', name: 'House Percussion 24 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-24.wav', category: 'percussions' },
  { id: 'perc-25', name: 'House Percussion 25 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-25.wav', category: 'percussions' },
  { id: 'perc-26', name: 'House Percussion 26 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-26.wav', category: 'percussions' },
  { id: 'perc-27', name: 'House Percussion 27 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-27.wav', category: 'percussions' },
  { id: 'perc-28', name: 'House Percussion 28 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-28.wav', category: 'percussions' },
  { id: 'perc-29', name: 'House Percussion 29 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-29.wav', category: 'percussions' },
  { id: 'perc-30', name: 'House Percussion 30 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-30.wav', category: 'percussions' },
  { id: 'perc-31', name: 'House Percussion 31 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-31.wav', category: 'percussions' },
  { id: 'perc-32', name: 'House Percussion 32 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-32.wav', category: 'percussions' },
  { id: 'perc-33', name: 'House Percussion 33 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-33.wav', category: 'percussions' },
  { id: 'perc-34', name: 'House Percussion 34 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-34.wav', category: 'percussions' },
  { id: 'perc-35', name: 'House Percussion 35 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-35.wav', category: 'percussions' },
  { id: 'perc-36', name: 'House Percussion 36 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-36.wav', category: 'percussions' },
  { id: 'perc-37', name: 'House Percussion 37 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-37.wav', category: 'percussions' },
  { id: 'perc-38', name: 'House Percussion 38 - Em or E', key: 'Em or E', path: '/samples/library/percussions/perc-38.wav', category: 'percussions' },
  { id: 'perc-39', name: 'House Percussion 39 - Em', key: 'Em', path: '/samples/library/percussions/perc-39.wav', category: 'percussions' },
  { id: 'perc-40', name: 'House Percussion 40 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-40.wav', category: 'percussions' },
  { id: 'perc-41', name: 'House Percussion 41 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-41.wav', category: 'percussions' },
  { id: 'perc-42', name: 'House Percussion 42 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-42.wav', category: 'percussions' },
  { id: 'perc-43', name: 'House Percussion 43 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-43.wav', category: 'percussions' },
  { id: 'perc-44', name: 'House Percussion 44 - F#m', key: 'F#m', path: '/samples/library/percussions/perc-44.wav', category: 'percussions' },
  { id: 'perc-45', name: 'House Percussion 45 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-45.wav', category: 'percussions' },
  { id: 'perc-46', name: 'House Percussion 46 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-46.wav', category: 'percussions' },
  { id: 'perc-47', name: 'House Percussion 47 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-47.wav', category: 'percussions' },
  { id: 'perc-48', name: 'House Percussion 48 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-48.wav', category: 'percussions' },
  { id: 'perc-49', name: 'House Percussion 49 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-49.wav', category: 'percussions' },
  { id: 'perc-50', name: 'House Percussion 50 - G#m', key: 'G#m', path: '/samples/library/percussions/perc-50.wav', category: 'percussions' },
  { id: 'perc-51', name: 'House Percussion 51 - Cm', key: 'Cm', path: '/samples/library/percussions/perc-51.wav', category: 'percussions' },
  { id: 'perc-52', name: 'House Percussion 52 - Cm', key: 'Cm', path: '/samples/library/percussions/perc-52.wav', category: 'percussions' },
  { id: 'perc-53', name: 'House Percussion 53 - Bm', key: 'Bm', path: '/samples/library/percussions/perc-53.wav', category: 'percussions' },
  { id: 'perc-54', name: 'House Percussion 54 - Cm', key: 'Cm', path: '/samples/library/percussions/perc-54.wav', category: 'percussions' },
  { id: 'perc-55', name: 'House Percussion 55 - G#', key: 'G#', path: '/samples/library/percussions/perc-55.wav', category: 'percussions' },
  { id: 'perc-56', name: 'House Percussion 56 - G#', key: 'G#', path: '/samples/library/percussions/perc-56.wav', category: 'percussions' },
  { id: 'perc-57', name: 'House Percussion 57 - G#', key: 'G#', path: '/samples/library/percussions/perc-57.wav', category: 'percussions' },
  { id: 'snap-01', name: 'House Snap 01 - C#m', key: 'C#m', path: '/samples/library/snaps/snap-01.wav', category: 'snaps' },
  { id: 'snap-02', name: 'House Snap 02 - G#m', key: 'G#m', path: '/samples/library/snaps/snap-02.wav', category: 'snaps' },
  { id: 'sfx-01', name: 'House SFX 01', key: '', path: '/samples/library/sfx/sfx-01.wav', category: 'sfx' },
  { id: 'sfx-02', name: 'House SFX 02 - F', key: 'F', path: '/samples/library/sfx/sfx-02.wav', category: 'sfx' },
  { id: 'sfx-03', name: 'House SFX 03 - F#', key: 'F#', path: '/samples/library/sfx/sfx-03.wav', category: 'sfx' },
  { id: 'sfx-04', name: 'House SFX 04 - Cm', key: 'Cm', path: '/samples/library/sfx/sfx-04.wav', category: 'sfx' },
  { id: 'sfx-05', name: 'House SFX 05', key: '', path: '/samples/library/sfx/sfx-05.wav', category: 'sfx' },
  { id: 'sfx-06', name: 'House SFX 06 - A#m', key: 'A#m', path: '/samples/library/sfx/sfx-06.wav', category: 'sfx' },
  { id: 'sfx-07', name: 'House SFX 07 - Fm or F', key: 'Fm or F', path: '/samples/library/sfx/sfx-07.wav', category: 'sfx' },
  { id: 'sfx-08', name: 'House SFX 08 - D#m', key: 'D#m', path: '/samples/library/sfx/sfx-08.wav', category: 'sfx' },
  { id: 'sfx-09', name: 'House SFX 09 - G#m', key: 'G#m', path: '/samples/library/sfx/sfx-09.wav', category: 'sfx' },
  { id: 'sfx-10', name: 'House SFX 10 - G#m', key: 'G#m', path: '/samples/library/sfx/sfx-10.wav', category: 'sfx' },
  { id: 'sfx-11', name: 'House SFX 11 - A#m', key: 'A#m', path: '/samples/library/sfx/sfx-11.wav', category: 'sfx' },
];

/**
 * Get all samples available for a specific voice
 */
export function getSamplesForVoice(voiceIndex: number): LibrarySample[] {
  const categories = VOICE_CATEGORIES[voiceIndex] ?? [];
  return SAMPLE_LIBRARY.filter(s => categories.includes(s.category));
}

/**
 * Find a sample by ID
 */
export function getSampleById(id: string): LibrarySample | undefined {
  return SAMPLE_LIBRARY.find(s => s.id === id);
}
